# Generated by Django 3.2.5 on 2021-08-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psc', models.CharField(max_length=100)),
                ('distance', models.CharField(max_length=100)),
                ('choice', models.CharField(max_length=100)),
            ],
        ),
    ]
